#---- TRECHO PARA CRIAR O DATABASE
CREATE SCHEMA `dbcsharp` DEFAULT CHARACTER SET utf8 ;

#---- TRECHO PARA CRIAR A TABELA EXEMPLO
CREATE TABLE `dbcsharp`.`pessoa` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(75) NOT NULL,
    `email` VARCHAR(75) NOT NULL,
    `telefone` VARCHAR(20) NOT NULL,
    `nascimento` DATE NOT NULL,
    PRIMARY KEY (`id`)
)  ENGINE=INNODB;

#---- TRECHO PARA RECUPERAR AS INFORMAÇÕES DE PESSOA
SELECT * FROM pessoa;

#---- TRECHO PARA APAGAR REGISTRO DE PESSOA
DELETE pessoa WHERE pessoa.id = ?;